<a href="https://colab.research.google.com/github/DEBANGANROY/minor_project/blob/main/Minor_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install bing-image-downloader

In [ ]:
!mkdir images

In [ ]:
# Web-Crawler - gathering data(Step 1)
from bing_image_downloader import downloader
downloader.download("motorbikes", limit =20, output_dir = 'images' , adult_filter_off = True)



[!!]Indexing page: 1

[%] Indexed 20 Images on Page 1.


[%] Downloading Image #1 from https://wp-assets.futurism.com/2019/01/ducati-futuristic-electric-motorcycle-1200x639.png
[%] File Downloaded !

[%] Downloading Image #2 from https://i.pinimg.com/736x/68/db/91/68db915241d8548ad2bf42d62b9f6398---motorbikes.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://i.ebayimg.com/00/s/NjAwWDgwMA==/z/O6kAAOSw13ldj4k9/$_86.PNG
[%] File Downloaded !

[%] Downloading Image #4 from https://i.pinimg.com/736x/04/97/26/04972631472ce404111e56123b2cab76--motorbikes.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://www.all4god.net/uploads/3/2/1/8/32183707/5470246.jpg?255
[%] File Downloaded !

[%] Downloading Image #6 from https://i.pinimg.com/736x/99/47/cd/9947cdb6863f7c259b38066f9100f73e.jpg
[%] File Downloaded !

[%] Downloading Image #7 from http://jap-express.com/upload/gallery/image_1527130815.jpg
[%] File Downloaded !

[%] Downloading Image #8 from http://farm8.stat

In [ ]:
downloader.download("flowers", limit = 20, output_dir = 'images' , adult_filter_off = True)

In [ ]:
from bing_image_downloader import downloader
downloader.download("ice cream cone", limit = 20, output_dir = 'images' , adult_filter_off = True) # adult_filter_off = True - not to get unwanted images



[!!]Indexing page: 1

[%] Indexed 12 Images on Page 1.


[%] Downloading Image #1 from https://townsquare.media/site/942/files/2018/07/Ice-Cream-Cone-TSM.jpg?w=1200&amp;h=0&amp;zc=1&amp;s=0&amp;a=t&amp;q=89
[%] File Downloaded !

[%] Downloading Image #2 from https://geekologie.com/2017/04/26/black-soft-serve-ice-cream-5.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://static.standard.co.uk/s3fs-public/thumbnails/image/2017/08/23/10/billionaires-ice-cream.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://static.boredpanda.com/blog/wp-content/uploads/2017/04/black-ice-cream-cone-little-damage-4-590085eb5e59a__700.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://the-glass-co.com/wp-content/uploads/2016/10/ice-cream-presentation.gif
[%] File Downloaded !

[%] Downloading Image #6 from https://d28mt5n9lkji5m.cloudfront.net/i/W4DviZ0U8k.jpg
[%] File Downloaded !

[%] Downloading Image #7 from https://cdn.shopify.com/s/files/1/3045/1030/produc

In [ ]:
# Preprocessing data(Step 2)

import os

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt

from skimage.io import imread
from skimage.transform import resize

In [ ]:
# Flattening
a = np.array([[1,2,3,4],
              [5,6,7,8]
              ])
a.ndim

2

In [ ]:
# how to flatten an matrix to vector(1d array)
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
# method 1
datadir = '/content/images'

categories = ['motorbikes', 'flowers', 'ice cream cone'] # write the categories you want to take from the folders

target = [] # output
flat_data = [] # input
images=[]

# accessing the data
i=0
for i in categories:
  class_num = categories.index(i) # label encoding the values

  path = os.path.join(datadir, i)
  
  for img in os.listdir(path):
   # print(img)
    img_array = imread(os.path.join(path,img))

    # image resizing
    img_resize = resize(img_array,(150, 150,3)) # Value gets converted 0-1 from 0-255

    # image flattening
    flat_data.append(np.ndarray.flatten(img_resize)) # flattening the images
    target.append(class_num)
    images.append(img_resize)
    
    #plt.imshow(img_resize)
    #plt.show()

# Convert into array

flat_data = np.array(flat_data)
target = np.array(target)
images = np.array(images)

In [ ]:
# split data into training and testing

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(flat_data, target,test_size = 0.3, random_state = 0) # taking faltened data for input

In [ ]:
from sklearn.model_selection import GridSearchCV
from sklearn import svm
param_grid = [
              {'C':[1, 10, 100, 1000], 'kernel': ['linear']},
              {'C':[1, 10, 100, 1000], 'gamma':[0.001, 0.0001], 'kernel': ['linear']}
]

svc = svm.SVC(probability=True)
clf = GridSearchCV(svc, param_grid)
clf.fit(x_train, y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=True, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']},
                         {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001],
                          'kernel': ['linear']}],
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [ ]:
y_pred = clf.predict(x_test)
y_pred

array([1, 0, 1, 1, 1, 2, 0, 0, 2, 1, 0, 0, 1, 0, 2, 2, 1, 0])

In [ ]:
y_test

array([1, 1, 2, 1, 0, 0, 1, 2, 2, 1, 0, 0, 1, 2, 1, 2, 2, 0])

In [ ]:
# evaluation

from sklearn.metrics import accuracy_score, confusion_matrix

In [ ]:
accuracy_score(y_pred, y_test)

0.5

In [ ]:
confusion_matrix(y_pred, y_test)

array([[3, 2, 2],
       [1, 4, 2],
       [1, 1, 2]])

In [ ]:
from xgboost import XGBClassifier
model = XGBClassifier()
model.fit(x_train,y_train)
y_pred = model.predict(x_test)
confusion_matrix(y_pred,y_test)
accuracy_score(y_pred,y_test)

0.2222222222222222

In [ ]:
# Saving model using pickel library

import pickle
pickle.dump(clf, open('img_model.p', 'wb')) # wb - writing byte

In [ ]:
model = pickle.load(open('img_model.p', 'rb')) # rb - reading byte

In [ ]:
#testing new image
flat_data = []
url = input('Enter your url: ')
img = imread(url)
img_resize = resize(img,(150,150,3))
flat_data.append(img_resize.flatten())
flat_data = np.array(flat_data)
print(img.shape)
plt.imshow(img_resize)
y_out = model.predict(flat_data)
y_out = categories[y_out[0]]
print(f'PREDICTED OUTPUT : {y_out}')